### ISSUE TITLE
Invalid stream configuration: stream name is required

### ISSUE THREAD

**Issue by hari0015** [pilsna/ais-for-geoevent#1]
I have tested it in 10.2 and found it working. Yesterday, I have updated  my geoevent processor to  latest 10.2.1from 10.2. After that  When I add  input connector it doesn't show the port  option and generate this 'Invalid stream configuration: stream name is required' error.

I would appreciate if you help me in this.

**Comment by pilsna** [comment]
I haven't tried it on 10.2.1 yet. 
Have you made sure that all the configuration properties of the input connector are shown?
![screen shot 2014-02-04 at 14 59 19](https://f.cloud.github.com/assets/118839/2076561/9bc7718c-8da4-11e3-9fc2-0a38a6f70671.png)

**Comment by hari0015** [comment]
Hi

Yes the configuration was set.  Please find the attached pictures of
 configuration and  input. By  default  transport appears as feature.  TCP
selection is made in transport field.

In Picture '202014-02-05 20at 20 6.43.02 20 am.png'  it doesn't show the
 port and other configuration when adding the input.

On Tue, Feb 4, 2014 at 10:00 PM, Nils Rydh notifications@github.com wrote:

> I haven't tried it on 10.2.1 yet.
> Have you made sure that all the configuration properties of the input
> connector are shown?
> [image: screen shot 2014-02-04 at 14 59 19]https://f.cloud.github.com/assets/118839/2076561/9bc7718c-8da4-11e3-9fc2-0a38a6f70671.png
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/pilsna/ais-for-geovent/issues/1#issuecomment-34061201
> .

## 

With Kind  Regards
Harish Kumar

**Comment by pilsna** [comment]
hmm, I can't see your picture, but I will try it, it'll take a couple of days before I get to it though...

**Comment by hari0015** [comment]
Thanks. I will eagerly wait for your  response.

On Wed, Feb 5, 2014 at 5:58 PM, Nils Rydh notifications@github.com wrote:

> hmm, I can't see your picture, but I will try it, it'll take a couple of
> days before I get to it though...
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/pilsna/ais-for-geovent/issues/1#issuecomment-34151829
> .

## 

With Kind  Regards
Harish Kumar

**Comment by pilsna** [comment]
I can reproduce your problem with 10.2.2.
With some help from the Esri Geoevent team, i got around to solving this bug:
http://forums.arcgis.com/threads/113453-Problem-upgrading-from-10.2.0-to-10.2.2-adapter-says-quot-Invalid-stream-configuration-quot

Please, try it out and see if it works for you.
